version: '2'
services:
  dokuwiki:
    image: 'docker.io/bitnami/dokuwiki:0-debian-10'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'dokuwiki_data:/bitnami'
volumes:
  dokuwiki_data:
    driver: local
